# ===================================
#  Relation Behavior Config
# ===================================

properties:
    label: 'offline.mall::lang.common.properties'
    deferredBinding: false
    showSorting: false
    view:
        list: $/offline/mall/models/property/columns.yaml
        toolbarButtons: add|create|remove
        defaultSort:
            column: sort_order
            direction: asc
    manage:
        form: $/offline/mall/models/property/fields.yaml
        recordsPerPage: 10
    pivot:
        form:
            fields:
                pivot[use_for_variants]:
                    label: 'offline.mall::lang.properties.use_for_variants'
                    comment: 'offline.mall::lang.properties.use_for_variants_comment'
                    type: switch
                    span: left
                pivot[filter_type]:
                    label: 'offline.mall::lang.properties.filter_type'
                    oc.commentPosition: ''
                    span: right
                    type: dropdown
