# ===================================
#  Relation Behavior Config
# ===================================

properties:
    label: 'offline.mall::lang.common.properties'
    deferredBinding: false
    showSorting: false
    view:
        list: $/offline/mall/models/property/columns_pivot.yaml
        toolbarButtons: add|create|remove
        defaultSort:
            column: sort_order
            direction: asc
    manage:
        form: $/offline/mall/models/property/fields_pivot.yaml
        recordsPerPage: 10
    pivot:
        form: $/offline/mall/models/property/fields_pivot.yaml
