language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source


before_script:
  - git clone https://github.com/octobercms/october.git
  - mkdir -p ./october/plugins/offline/mall
  - mv !(october) october/plugins/offline/mall
  - cd october
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - cd plugins/offline/mall
  - composer install

script: ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml
script: vendor/bin/phpunit
